import { KnowledgeMapGraph } from '../types/knowledgeMap';

export const HEART_FAILURE_MAP_FIXTURE: KnowledgeMapGraph = {
  id: 'heart-heart-failure',
  rootNodeId: 'heart-failure',
  specialtyId: 'heart',
  specialtyName: 'Cardiology',
  topicId: 'heart-failure',
  topicName: 'Heart Failure',
  generatedAt: new Date().toISOString(),
  version: 1,
  source: 'topic-guide',
  isExpandable: true,
  nodes: [
    {
      id: 'heart-failure',
      label: 'Heart Failure',
      type: 'root',
      summary: 'Clinical syndrome characterized by structural or functional impairment of ventricular filling or ejection of blood.',
      depth: 0,
      selectable: true,
      priority: 'primary',
    },
    // Sections (Depth 1)
    {
      id: 'hf-etiology',
      label: 'Etiology & Triggers',
      type: 'section',
      summary: 'Underlying causes including ischemic heart disease, hypertension, and valvular disorders.',
      parentId: 'heart-failure',
      depth: 1,
      selectable: true,
    },
    {
      id: 'hf-presentation',
      label: 'Clinical Presentation',
      type: 'section',
      summary: 'Cardinal signs including dyspnea on exertion, orthopnea, PND, and peripheral edema.',
      parentId: 'heart-failure',
      depth: 1,
      selectable: true,
    },
    {
      id: 'hf-investigations',
      label: 'Diagnostic Workup',
      type: 'investigation',
      summary: 'Essential investigations including BNP/NT-proBNP, transthoracic echocardiogram, and ECG.',
      parentId: 'heart-failure',
      depth: 1,
      selectable: true,
    },
    {
      id: 'hf-management',
      label: 'Guideline Therapy',
      type: 'treatment',
      summary: 'Guideline-directed medical therapy (GDMT) including quadruple therapy for HFrEF.',
      parentId: 'heart-failure',
      depth: 1,
      selectable: true,
    },
    {
      id: 'hf-red-flags',
      label: 'Acute Decompensation',
      type: 'red-flag',
      summary: 'Flash pulmonary edema, cardiogenic shock, and severe refractory hypoxia.',
      parentId: 'heart-failure',
      depth: 1,
      selectable: true,
    },

    // Sub-concepts (Depth 2)
    {
      id: 'hf-ischemic',
      label: 'Ischemic Disease',
      type: 'concept',
      summary: 'Most common etiology of left ventricular systolic dysfunction.',
      parentId: 'hf-etiology',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-hypertension',
      label: 'Hypertension',
      type: 'concept',
      summary: 'Chronic pressure overload leading to LV hypertrophy and HFpEF.',
      parentId: 'hf-etiology',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-dyspnea',
      label: 'Dyspnea & Orthopnea',
      type: 'finding',
      summary: 'Elevated left atrial and pulmonary capillary wedge pressures.',
      parentId: 'hf-presentation',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-edema',
      label: 'Peripheral Edema',
      type: 'finding',
      summary: 'Systemic venous congestion and sodium retention.',
      parentId: 'hf-presentation',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-bnp',
      label: 'BNP / NT-proBNP',
      type: 'investigation',
      summary: 'Biomarker of myocardial wall stress; rule-out threshold < 100 pg/mL.',
      parentId: 'hf-investigations',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-echo',
      label: 'Echocardiogram',
      type: 'investigation',
      summary: 'Evaluates LVEF, chamber dimensions, diastolic function, and valvular pathology.',
      parentId: 'hf-investigations',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-gdmt',
      label: 'Quadruple GDMT',
      type: 'treatment',
      summary: 'ARNI/ACEi + Beta-blocker + MRA + SGLT2i with mortality reduction.',
      parentId: 'hf-management',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-diuretics',
      label: 'Loop Diuretics',
      type: 'drug',
      summary: 'Furosemide / Bumetanide for symptomatic relief of fluid overload.',
      parentId: 'hf-management',
      depth: 2,
      selectable: true,
    },
    {
      id: 'hf-shock',
      label: 'Cardiogenic Shock',
      type: 'red-flag',
      summary: 'Hypoperfusion with SBP < 90 mmHg requiring inotropes or mechanical support.',
      parentId: 'hf-red-flags',
      depth: 2,
      selectable: true,
    },
  ],
  edges: [
    { id: 'e-root-etiology', source: 'heart-failure', target: 'hf-etiology', type: 'contains' },
    { id: 'e-root-pres', source: 'heart-failure', target: 'hf-presentation', type: 'presents-with' },
    { id: 'e-root-inv', source: 'heart-failure', target: 'hf-investigations', type: 'diagnosed-by' },
    { id: 'e-root-mgmt', source: 'heart-failure', target: 'hf-management', type: 'treated-with' },
    { id: 'e-root-rf', source: 'heart-failure', target: 'hf-red-flags', type: 'complicated-by' },

    { id: 'e-et-isch', source: 'hf-etiology', target: 'hf-ischemic', type: 'causes' },
    { id: 'e-et-htn', source: 'hf-etiology', target: 'hf-hypertension', type: 'causes' },
    { id: 'e-pr-dys', source: 'hf-presentation', target: 'hf-dyspnea', type: 'presents-with' },
    { id: 'e-pr-ede', source: 'hf-presentation', target: 'hf-edema', type: 'presents-with' },
    { id: 'e-in-bnp', source: 'hf-investigations', target: 'hf-bnp', type: 'diagnosed-by' },
    { id: 'e-in-ech', source: 'hf-investigations', target: 'hf-echo', type: 'diagnosed-by' },
    { id: 'e-mg-gdm', source: 'hf-management', target: 'hf-gdmt', type: 'treated-with' },
    { id: 'e-mg-diu', source: 'hf-management', target: 'hf-diuretics', type: 'treated-with' },
    { id: 'e-rf-shk', source: 'hf-red-flags', target: 'hf-shock', type: 'complicated-by' },
  ],
};

export const ASTHMA_MAP_FIXTURE: KnowledgeMapGraph = {
  id: 'pulm-asthma-acute',
  rootNodeId: 'asthma-acute',
  specialtyId: 'pulmonology',
  specialtyName: 'Pulmonology',
  topicId: 'asthma-acute',
  topicName: 'Acute Asthma Exacerbation',
  generatedAt: new Date().toISOString(),
  version: 1,
  source: 'topic-guide',
  isExpandable: true,
  nodes: [
    {
      id: 'asthma-acute',
      label: 'Acute Asthma Exacerbation',
      type: 'root',
      summary: 'Acute or subacute worsening of respiratory symptoms with airflow limitation.',
      depth: 0,
      selectable: true,
    },
    {
      id: 'asthma-assessment',
      label: 'Severity Assessment',
      type: 'investigation',
      summary: 'PEFR measurement, accessory muscle use, ability to complete sentences.',
      parentId: 'asthma-acute',
      depth: 1,
      selectable: true,
    },
    {
      id: 'asthma-treatment',
      label: 'Immediate Treatment',
      type: 'treatment',
      summary: 'High-dose inhaled SABA + SAMA, systemic corticosteroids, oxygen.',
      parentId: 'asthma-acute',
      depth: 1,
      selectable: true,
    },
    {
      id: 'asthma-red-flags',
      label: 'Life-Threatening Features',
      type: 'red-flag',
      summary: 'Silent chest, cyanosis, exhaustion, altered mental status, normal/high PaCO2.',
      parentId: 'asthma-acute',
      depth: 1,
      selectable: true,
    },
  ],
  edges: [
    { id: 'e-asthma-ass', source: 'asthma-acute', target: 'asthma-assessment', type: 'diagnosed-by' },
    { id: 'e-asthma-tx', source: 'asthma-acute', target: 'asthma-treatment', type: 'treated-with' },
    { id: 'e-asthma-rf', source: 'asthma-acute', target: 'asthma-red-flags', type: 'complicated-by' },
  ],
};

export const MALFORMED_GRAPH_FIXTURE: any = {
  id: 'malformed-graph',
  rootNodeId: 'missing-root',
  version: 0,
  source: 'ai-generated',
  nodes: [
    { id: 'node-1', label: 'Node 1 with very long redundant text repeating '.repeat(6), type: 'invalid_type', depth: 0 },
    { id: 'node-1', label: 'Duplicate Node 1', type: 'concept', depth: 1 }, // duplicate ID
    { id: 'node-2', label: 'Node 2', type: 'treatment', depth: 1, summary: 'Summary text '.repeat(60) },
  ],
  edges: [
    { id: 'e-1', source: 'node-1', target: 'node-2', type: 'invalid_edge_type', confidence: 5.5 }, // out of bounds confidence
    { id: 'e-2', source: 'node-1', target: 'node-1', type: 'contains' }, // self loop
    { id: 'e-3', source: 'node-1', target: 'missing-node-3', type: 'causes' }, // missing target
  ],
};

export const EMPTY_GRAPH_FIXTURE: KnowledgeMapGraph = {
  id: 'empty-topic',
  rootNodeId: 'empty-topic',
  generatedAt: new Date().toISOString(),
  version: 1,
  source: 'topic-guide',
  nodes: [],
  edges: [],
};
